name: flutter_weather
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_map: ^8.3.0
  flutter_riverpod: ^3.3.1
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_fonts: ^8.0.2
  http: ^1.6.0
  intl: ^0.20.2
  latlong2: ^0.9.1
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
